name: Add bugs to bugs project

on:
  issues:
    types:
      - opened
      - labeled
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - id: create_token
        uses: tibdex/github-app-token@v2
      - run: "echo 'The created token is masked: ${{ steps.create_token.outputs.token }}'"
